#.travis.yml
sudo: required
language: node_js
dist: trusty
node_js:
  - "6"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - npm install -g @angular/cli
  - npm install coveralls
  - npm install codacy-coverage
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - ng lint
  - ng test --single-run true --code-coverage
  - ng e2e

after_success:
  - cat ./dist/reports/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - cat ./dist/reports/coverage/lcov.info | ./node_modules/.bin/codacy-coverage